# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3227a586420fcd828c3f3672c8ec686985d7981de0ebfbaaf1aa42442cece7304ac2a9eefb85b933359f153a66b53c2729b9f0f774b4b120d2469e48d77c3472

test:
  secret_key_base: 2b1a6cd4b93c47564326db2c0aab8940d02f03b2564aee4741dc678e56ca866faf6d74c2ce2d2d776e8cb6768fbc9037ede1ca10091bd60e807959f7bf788428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
